name: GMIPCore
version: '0.0.1'
main: net.gmip.core.GMIPCore
api-version: '1.21'

commands:
  gmip:
    description: GMIPCore command
    usage: /<command>
  ps:
    description: Redirect to /claimfly
    subcommands:
      fly:
        description: Activa el vuelo.
        usage: /ps fly