name: Discord

on:
  - push

jobs:
  disord_test_message:
    runs-on: ubuntu-latest
    name: discord commits
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Send commit to Discord
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          message: "Nuevo commit en {{ github.context.payload.repository.name }} por {{ commit.author.name }}"
          embed: |
            {
              "title": "Commit Details",
              "description": "{{ commit.message }}",
              "url": "{{ commit.url }}",
              "author": {
                "name": "{{ commit.author.name }}",
                "icon_url": "{{ commit.author.avatar_url }}"
              },
              "fields": [
                {
                  "name": "Commit ID",
                  "value": "{{ commit.id }}",
                  "inline": true
                },
                {
                  "name": "Timestamp",
                  "value": "{{ commit.timestamp }}",
                  "inline": true
                }
              ]
            }
          include-extras: true